//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitDotNet.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitDotNet.Tests.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;Applications/ss04fto6lzk5/Pages/bkvwwmdlhy0o/Fields/uaco8nhss095.json&quot;,
        ///  &quot;$type&quot;: &quot;Models.Software.Field&quot;,
        ///  &quot;a&quot;: [
        ///    {
        ///      &quot;$id&quot;: &quot;46673488&quot;,
        ///      &quot;b&quot;: {
        ///        &quot;$id&quot;: &quot;1769254&quot;,
        ///        &quot;isVisible&quot;: true
        ///      }
        ///    },
        ///    {
        ///      &quot;$id&quot;: &quot;51554043&quot;,
        ///      &quot;b&quot;: {
        ///        &quot;$id&quot;: &quot;44465472&quot;
        ///      }
        ///    },
        ///    {
        ///      &quot;$id&quot;: &quot;38362957&quot;,
        ///      &quot;b&quot;: {
        ///        &quot;$id&quot;: &quot;1578659&quot;,
        ///        &quot;isVisible&quot;: true
        ///      }
        ///    }
        ///  ],
        ///  &quot;someValue&quot;: {
        ///    &quot;$id&quot;: &quot;31541549&quot;,
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlobContent {
            get {
                return ResourceManager.GetString("BlobContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43.
        /// </summary>
        internal static string BlobPosition {
            get {
                return ResourceManager.GetString("BlobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CommitGraph {
            get {
                object obj = ResourceManager.GetObject("CommitGraph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CompleteRepository {
            get {
                object obj = ResourceManager.GetObject("CompleteRepository", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CompleteRepositoryWithRename {
            get {
                object obj = ResourceManager.GetObject("CompleteRepositoryWithRename", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CompleteRepositoryWithStash {
            get {
                object obj = ResourceManager.GetObject("CompleteRepositoryWithStash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BenchmarkRepository {
            get {
                object obj = ResourceManager.GetObject("BenchmarkRepository", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CompleteMergeRepository {
            get {
                object obj = ResourceManager.GetObject("CompleteMergeRepository", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Index {
            get {
                object obj = ResourceManager.GetObject("Index", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foo.
        /// </summary>
        internal static string LooseBlobContent {
            get {
                return ResourceManager.GetString("LooseBlobContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LooseBlobData {
            get {
                object obj = ResourceManager.GetObject("LooseBlobData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MergeCommitGraph {
            get {
                object obj = ResourceManager.GetObject("MergeCommitGraph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MultiParentMergeCommitGraph {
            get {
                object obj = ResourceManager.GetObject("MultiParentMergeCommitGraph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;Applications/f3agr4hyae6c/Pages/wdfxdkzgx9er/Fields/1d1pin851gnw.json&quot;,
        ///  &quot;$type&quot;: &quot;Models.Software.Field&quot;,
        ///  &quot;a&quot;: [
        ///    {
        ///      &quot;$id&quot;: &quot;6077342&quot;,
        ///      &quot;b&quot;: {
        ///        &quot;$id&quot;: &quot;34141142&quot;,
        ///        &quot;isVisible&quot;: true
        ///      }
        ///    },
        ///    {
        ///      &quot;$id&quot;: &quot;28050140&quot;,
        ///      &quot;b&quot;: {
        ///        &quot;$id&quot;: &quot;59583651&quot;
        ///      }
        ///    },
        ///    {
        ///      &quot;$id&quot;: &quot;15159042&quot;,
        ///      &quot;b&quot;: {
        ///        &quot;$id&quot;: &quot;48195579&quot;,
        ///        &quot;isVisible&quot;: true
        ///      }
        ///    }
        ///  ],
        ///  &quot;someValue&quot;: {
        ///    &quot;$id&quot;: &quot;27370998&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OfsDeltaContent {
            get {
                return ResourceManager.GetString("OfsDeltaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 151.
        /// </summary>
        internal static string OfsDeltaPosition {
            get {
                return ResourceManager.GetString("OfsDeltaPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Pack {
            get {
                object obj = ResourceManager.GetObject("Pack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PackIndex {
            get {
                object obj = ResourceManager.GetObject("PackIndex", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
